"""added_noon_sellers_and_columns

Revision ID: 2b1a30222c98
Revises: 956ddbd00004
Create Date: 2026-06-30 15:19:19.981459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b1a30222c98'
down_revision: Union[str, Sequence[str], None] = '956ddbd00004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplace_sellers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('marketplace', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=15), server_default=sa.text("'UAE'"), nullable=False),
    sa.Column('external_store_id', sa.String(length=100), nullable=True),
    sa.Column('store_name', sa.String(length=200), nullable=False),
    sa.Column('store_slug', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('marketplace', 'country', 'external_store_id', name='uq_marketplace_seller')
    )
    op.create_index(op.f('ix_marketplace_sellers_external_store_id'), 'marketplace_sellers', ['external_store_id'], unique=False)
    op.create_index(op.f('ix_marketplace_sellers_marketplace'), 'marketplace_sellers', ['marketplace'], unique=False)
    op.create_table('user_stores',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('marketplace', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=30), nullable=False),
    sa.Column('store_name', sa.String(length=200), nullable=False),
    sa.Column('store_slug', sa.String(length=100), nullable=True),
    sa.Column('external_store_id', sa.String(length=100), nullable=True),
    sa.Column('store_url', sa.String(length=1000), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'marketplace', 'external_store_id', name='uq_user_store')
    )
    op.create_index(op.f('ix_user_stores_user_id'), 'user_stores', ['user_id'], unique=False)
    op.add_column('alerts', sa.Column('previous_value', sa.NUMERIC(precision=10, scale=2), nullable=True))
    op.add_column('alerts', sa.Column('current_value', sa.NUMERIC(precision=10, scale=2), nullable=True))
    op.add_column('alerts', sa.Column('change_pct', sa.NUMERIC(precision=7, scale=2), nullable=True))
    op.add_column('alerts', sa.Column('threshold_used', sa.NUMERIC(precision=5, scale=2), nullable=True))
    op.add_column('competitor_listings', sa.Column('marketplace_seller_id', sa.UUID(), nullable=True))
    op.add_column('competitor_listings', sa.Column('name', sa.String(length=500), nullable=True))
    op.add_column('competitor_listings', sa.Column('platform_sku', sa.String(length=50), nullable=True))
    op.add_column('competitor_listings', sa.Column('category', sa.String(length=300), nullable=True))
    op.add_column('competitor_listings', sa.Column('image_url', sa.String(length=1000), nullable=True))
    op.add_column('competitor_listings', sa.Column('last_seen_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'competitor_listings', 'marketplace_sellers', ['marketplace_seller_id'], ['id'], ondelete='SET NULL')
    op.add_column('price_snapshots', sa.Column('discount_pct', sa.NUMERIC(precision=5, scale=2), nullable=True))
    op.add_column('price_snapshots', sa.Column('search_position', sa.SMALLINT(), nullable=True))
    op.alter_column('price_snapshots', 'original_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.add_column('tracked_products', sa.Column('store_id', sa.UUID(), nullable=False))
    op.add_column('tracked_products', sa.Column('platform_sku', sa.String(length=50), nullable=True))
    op.add_column('tracked_products', sa.Column('image_url', sa.String(length=1000), nullable=True))
    op.add_column('tracked_products', sa.Column('last_seen_at', sa.DateTime(), nullable=True))
    op.alter_column('tracked_products', 'category',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=300),
               existing_nullable=True)
    op.drop_index(op.f('ix_tracked_products_user_id'), table_name='tracked_products')
    op.create_index(op.f('ix_tracked_products_store_id'), 'tracked_products', ['store_id'], unique=False)
    op.drop_constraint(op.f('tracked_products_user_id_fkey'), 'tracked_products', type_='foreignkey')
    op.create_foreign_key(None, 'tracked_products', 'user_stores', ['store_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tracked_products', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracked_products', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tracked_products', type_='foreignkey')
    op.create_foreign_key(op.f('tracked_products_user_id_fkey'), 'tracked_products', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_tracked_products_store_id'), table_name='tracked_products')
    op.create_index(op.f('ix_tracked_products_user_id'), 'tracked_products', ['user_id'], unique=False)
    op.alter_column('tracked_products', 'category',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('tracked_products', 'last_seen_at')
    op.drop_column('tracked_products', 'image_url')
    op.drop_column('tracked_products', 'platform_sku')
    op.drop_column('tracked_products', 'store_id')
    op.alter_column('price_snapshots', 'original_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
    op.drop_column('price_snapshots', 'search_position')
    op.drop_column('price_snapshots', 'discount_pct')
    op.drop_constraint(None, 'competitor_listings', type_='foreignkey')
    op.drop_column('competitor_listings', 'last_seen_at')
    op.drop_column('competitor_listings', 'image_url')
    op.drop_column('competitor_listings', 'category')
    op.drop_column('competitor_listings', 'platform_sku')
    op.drop_column('competitor_listings', 'name')
    op.drop_column('competitor_listings', 'marketplace_seller_id')
    op.drop_column('alerts', 'threshold_used')
    op.drop_column('alerts', 'change_pct')
    op.drop_column('alerts', 'current_value')
    op.drop_column('alerts', 'previous_value')
    op.drop_index(op.f('ix_user_stores_user_id'), table_name='user_stores')
    op.drop_table('user_stores')
    op.drop_index(op.f('ix_marketplace_sellers_marketplace'), table_name='marketplace_sellers')
    op.drop_index(op.f('ix_marketplace_sellers_external_store_id'), table_name='marketplace_sellers')
    op.drop_table('marketplace_sellers')
    # ### end Alembic commands ###
