"""Added two new tables product_price_snapshot and listing_signal

Revision ID: 5bad92d48d20
Revises: 98f83168be91
Create Date: 2026-07-21 23:04:41.332640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5bad92d48d20'
down_revision: Union[str, Sequence[str], None] = '98f83168be91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracked_product_snapshots',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tracked_product_id', sa.UUID(), nullable=False),
    sa.Column('scrape_job_id', sa.UUID(), nullable=True),
    sa.Column('price', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('original_price', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=15), server_default='PKR', nullable=False),
    sa.Column('stock_status', sa.String(length=50), server_default=sa.text("'unknown'"), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('source', sa.String(length=20), server_default=sa.text("'manual'"), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('manual', 'scraped')", name='ck_tracked_product_snapshots_source'),
    sa.CheckConstraint("stock_status IN ('in_stock', 'out_of_stock', 'limited', 'unknown')", name='ck_tracked_product_snapshots_stock_status'),
    sa.CheckConstraint('rating IS NULL OR (rating >= 0 AND rating <= 5)', name='ck_tracked_product_snapshots_rating'),
    sa.ForeignKeyConstraint(['scrape_job_id'], ['scrape_jobs.id'], ),
    sa.ForeignKeyConstraint(['tracked_product_id'], ['tracked_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracked_product_snapshots_tracked_product_id'), 'tracked_product_snapshots', ['tracked_product_id'], unique=False)
    op.create_table('listing_signals',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('competitor_listing_id', sa.UUID(), nullable=False),
    sa.Column('price_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('nudges', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('warranty', sa.Text(), nullable=True),
    sa.Column('partner_rating', sa.NUMERIC(precision=4, scale=2), nullable=True),
    sa.Column('positive_seller_rating', sa.Integer(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competitor_listing_id'], ['competitor_listings.id'], ),
    sa.ForeignKeyConstraint(['price_snapshot_id'], ['price_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_signals_competitor_listing_id'), 'listing_signals', ['competitor_listing_id'], unique=False)
    op.create_index(op.f('ix_listing_signals_price_snapshot_id'), 'listing_signals', ['price_snapshot_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listing_signals_price_snapshot_id'), table_name='listing_signals')
    op.drop_index(op.f('ix_listing_signals_competitor_listing_id'), table_name='listing_signals')
    op.drop_table('listing_signals')
    op.drop_index(op.f('ix_tracked_product_snapshots_tracked_product_id'), table_name='tracked_product_snapshots')
    op.drop_table('tracked_product_snapshots')
    # ### end Alembic commands ###
