"""add_last_discovered_at_to_tracked_products

Revision ID: 4f2dc6b7d635
Revises: e40d05890b95
Create Date: 2026-09-22 14:35:50.747882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f2dc6b7d635'
down_revision: Union[str, Sequence[str], None] = 'e40d05890b95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracked_products', sa.Column('last_discovered_at', sa.DateTime(timezone=True), nullable=True, comment='NULL = never discovered. Set after a successful discovery run.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracked_products', 'last_discovered_at')
    # ### end Alembic commands ###
