"""add_pre_order_to_stock_status

Revision ID: 956ddbd00004
Revises: ba53bd9e328c
Create Date: 2026-05-21 09:21:54.574349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '956ddbd00004'
down_revision: Union[str, Sequence[str], None] = 'ba53bd9e328c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
