"""added two new tables and added columns in price_snapshot table

Revision ID: 98f83168be91
Revises: 2ca9dfdd8613
Create Date: 2026-07-13 15:50:17.151488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98f83168be91'
down_revision: Union[str, Sequence[str], None] = '2ca9dfdd8613'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_snapshots', sa.Column('stock_count', sa.Integer(), nullable=True))
    op.add_column('price_snapshots', sa.Column('is_lowest_price_nudge', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('price_snapshots', sa.Column('low_stock_nudge_value', sa.Integer(), nullable=True))
    op.add_column('price_snapshots', sa.Column('delivery_estimate', sa.Text(), nullable=True))
    op.add_column('scrape_jobs', sa.Column('target_identifier', sa.String(length=500), nullable=True))
    op.add_column('scrape_jobs', sa.Column('pages_scraped', sa.SMALLINT(), nullable=True))
    op.add_column('scrape_jobs', sa.Column('items_found', sa.Integer(), nullable=True))
    op.add_column('scrape_jobs', sa.Column('items_updated', sa.Integer(), nullable=True))
    op.add_column('scrape_jobs', sa.Column('alerts_triggered', sa.Integer(), nullable=True))
    op.add_column('scrape_jobs', sa.Column('duration_secs', sa.NUMERIC(precision=8, scale=3), nullable=True))
    op.add_column('scrape_jobs', sa.Column('error_detail', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scrape_jobs', 'error_detail')
    op.drop_column('scrape_jobs', 'duration_secs')
    op.drop_column('scrape_jobs', 'alerts_triggered')
    op.drop_column('scrape_jobs', 'items_updated')
    op.drop_column('scrape_jobs', 'items_found')
    op.drop_column('scrape_jobs', 'pages_scraped')
    op.drop_column('scrape_jobs', 'target_identifier')
    op.drop_column('price_snapshots', 'delivery_estimate')
    op.drop_column('price_snapshots', 'low_stock_nudge_value')
    op.drop_column('price_snapshots', 'is_lowest_price_nudge')
    op.drop_column('price_snapshots', 'stock_count')
    # ### end Alembic commands ###
