"""added verification tracking fields,added render_type field, added extraction tracking fields to scrape_jobs

Revision ID: b7596b093241
Revises: a444fd8208ae
Create Date: 2026-05-17 13:56:50.969755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7596b093241'
down_revision: Union[str, Sequence[str], None] = 'a444fd8208ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_alerts_listing'), table_name='alerts')
    op.drop_index(op.f('idx_alerts_user'), table_name='alerts')
    op.create_index(op.f('ix_alerts_competitor_listing_id'), 'alerts', ['competitor_listing_id'], unique=False)
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.drop_constraint(op.f('alerts_user_id_fkey'), 'alerts', type_='foreignkey')
    op.drop_constraint(op.f('alerts_price_snapshot_id_fkey'), 'alerts', type_='foreignkey')
    op.create_foreign_key(None, 'alerts', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'alerts', 'competitor_listings', ['competitor_listing_id'], ['id'])
    op.create_foreign_key(None, 'alerts', 'price_snapshots', ['price_snapshot_id'], ['id'])
    op.add_column('competitor_listings', sa.Column('discovered_api_endpoint', sa.Text(), nullable=True))
    op.add_column('competitor_listings', sa.Column('render_type', sa.String(length=50), server_default=sa.text("'unknown'"), nullable=False))
    op.drop_constraint(op.f('competitor_listings_tracked_product_id_url_key'), 'competitor_listings', type_='unique')
    op.drop_index(op.f('idx_competitor_listings_active'), table_name='competitor_listings')
    op.drop_index(op.f('idx_competitor_listings_platform'), table_name='competitor_listings')
    op.drop_index(op.f('idx_competitor_listings_product'), table_name='competitor_listings')
    op.create_index(op.f('ix_competitor_listings_tracked_product_id'), 'competitor_listings', ['tracked_product_id'], unique=False)
    op.drop_constraint(op.f('competitor_listings_tracked_product_id_fkey'), 'competitor_listings', type_='foreignkey')
    op.drop_constraint(op.f('competitor_listings_extraction_config_id_fkey'), 'competitor_listings', type_='foreignkey')
    op.create_foreign_key(None, 'competitor_listings', 'tracked_products', ['tracked_product_id'], ['id'])
    op.create_foreign_key(None, 'competitor_listings', 'extraction_configs', ['extraction_config_id'], ['id'])
    op.add_column('extraction_configs', sa.Column('verified_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('extraction_configs', sa.Column('status', sa.String(length=60), server_default=sa.text("'probationary'"), nullable=False))
    op.drop_index(op.f('idx_price_snapshots_listing'), table_name='price_snapshots')
    op.drop_index(op.f('idx_price_snapshots_listing_time'), table_name='price_snapshots')
    op.drop_index(op.f('idx_price_snapshots_scraped_at'), table_name='price_snapshots')
    op.create_index(op.f('ix_price_snapshots_competitor_listing_id'), 'price_snapshots', ['competitor_listing_id'], unique=False)
    op.drop_constraint(op.f('price_snapshots_scrape_job_id_fkey'), 'price_snapshots', type_='foreignkey')
    op.create_foreign_key(None, 'price_snapshots', 'scrape_jobs', ['scrape_job_id'], ['id'])
    op.create_foreign_key(None, 'price_snapshots', 'competitor_listings', ['competitor_listing_id'], ['id'])
    op.drop_index(op.f('idx_proxies_health'), table_name='proxies', postgresql_where='(is_active = true)')
    op.add_column('scrape_jobs', sa.Column('extraction_method_used', sa.String(length=60), nullable=True))
    op.add_column('scrape_jobs', sa.Column('extraction_step_reached', sa.Integer(), nullable=True))
    op.drop_index(op.f('idx_scrape_jobs_listing'), table_name='scrape_jobs')
    op.drop_index(op.f('idx_scrape_jobs_scheduled'), table_name='scrape_jobs', postgresql_where="((status)::text = 'pending'::text)")
    op.drop_index(op.f('idx_scrape_jobs_status'), table_name='scrape_jobs')
    op.create_index(op.f('ix_scrape_jobs_competitor_listing_id'), 'scrape_jobs', ['competitor_listing_id'], unique=False)
    op.drop_constraint(op.f('scrape_jobs_profile_id_fkey'), 'scrape_jobs', type_='foreignkey')
    op.drop_constraint(op.f('fk_result_snapshot'), 'scrape_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'scrape_jobs', 'scraper_profiles', ['profile_id'], ['id'])
    op.create_foreign_key(None, 'scrape_jobs', 'price_snapshots', ['result_snapshot_id'], ['id'])
    op.create_foreign_key(None, 'scrape_jobs', 'competitor_listings', ['competitor_listing_id'], ['id'])
    op.drop_index(op.f('idx_scraper_profiles_domain'), table_name='scraper_profiles')
    op.drop_index(op.f('idx_scraper_profiles_health'), table_name='scraper_profiles', postgresql_where='(is_burned = false)')
    op.drop_constraint(op.f('scraper_profiles_proxy_id_fkey'), 'scraper_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'scraper_profiles', 'proxies', ['proxy_id'], ['id'])
    op.drop_index(op.f('idx_tracked_products_user'), table_name='tracked_products')
    op.create_index(op.f('ix_tracked_products_user_id'), 'tracked_products', ['user_id'], unique=False)
    op.drop_constraint(op.f('tracked_products_user_id_fkey'), 'tracked_products', type_='foreignkey')
    op.create_foreign_key(None, 'tracked_products', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.drop_constraint(None, 'tracked_products', type_='foreignkey')
    op.create_foreign_key(op.f('tracked_products_user_id_fkey'), 'tracked_products', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_tracked_products_user_id'), table_name='tracked_products')
    op.create_index(op.f('idx_tracked_products_user'), 'tracked_products', ['user_id'], unique=False)
    op.drop_constraint(None, 'scraper_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('scraper_profiles_proxy_id_fkey'), 'scraper_profiles', 'proxies', ['proxy_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('idx_scraper_profiles_health'), 'scraper_profiles', ['domain', 'health_score'], unique=False, postgresql_where='(is_burned = false)')
    op.create_index(op.f('idx_scraper_profiles_domain'), 'scraper_profiles', ['domain'], unique=False)
    op.drop_constraint(None, 'scrape_jobs', type_='foreignkey')
    op.drop_constraint(None, 'scrape_jobs', type_='foreignkey')
    op.drop_constraint(None, 'scrape_jobs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_result_snapshot'), 'scrape_jobs', 'price_snapshots', ['result_snapshot_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('scrape_jobs_profile_id_fkey'), 'scrape_jobs', 'scraper_profiles', ['profile_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_scrape_jobs_competitor_listing_id'), table_name='scrape_jobs')
    op.create_index(op.f('idx_scrape_jobs_status'), 'scrape_jobs', ['status'], unique=False)
    op.create_index(op.f('idx_scrape_jobs_scheduled'), 'scrape_jobs', ['scheduled_at'], unique=False, postgresql_where="((status)::text = 'pending'::text)")
    op.create_index(op.f('idx_scrape_jobs_listing'), 'scrape_jobs', ['competitor_listing_id'], unique=False)
    op.drop_column('scrape_jobs', 'extraction_step_reached')
    op.drop_column('scrape_jobs', 'extraction_method_used')
    op.create_index(op.f('idx_proxies_health'), 'proxies', ['health_score'], unique=False, postgresql_where='(is_active = true)')
    op.drop_constraint(None, 'price_snapshots', type_='foreignkey')
    op.drop_constraint(None, 'price_snapshots', type_='foreignkey')
    op.create_foreign_key(op.f('price_snapshots_scrape_job_id_fkey'), 'price_snapshots', 'scrape_jobs', ['scrape_job_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_price_snapshots_competitor_listing_id'), table_name='price_snapshots')
    op.create_index(op.f('idx_price_snapshots_scraped_at'), 'price_snapshots', [sa.literal_column('scraped_at DESC')], unique=False)
    op.create_index(op.f('idx_price_snapshots_listing_time'), 'price_snapshots', ['competitor_listing_id', sa.literal_column('scraped_at DESC')], unique=False)
    op.create_index(op.f('idx_price_snapshots_listing'), 'price_snapshots', ['competitor_listing_id'], unique=False)
    op.drop_column('extraction_configs', 'status')
    op.drop_column('extraction_configs', 'verified_count')
    op.drop_constraint(None, 'competitor_listings', type_='foreignkey')
    op.drop_constraint(None, 'competitor_listings', type_='foreignkey')
    op.create_foreign_key(op.f('competitor_listings_extraction_config_id_fkey'), 'competitor_listings', 'extraction_configs', ['extraction_config_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('competitor_listings_tracked_product_id_fkey'), 'competitor_listings', 'tracked_products', ['tracked_product_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_competitor_listings_tracked_product_id'), table_name='competitor_listings')
    op.create_index(op.f('idx_competitor_listings_product'), 'competitor_listings', ['tracked_product_id'], unique=False)
    op.create_index(op.f('idx_competitor_listings_platform'), 'competitor_listings', ['platform'], unique=False)
    op.create_index(op.f('idx_competitor_listings_active'), 'competitor_listings', ['is_active', 'confirmed_by_user'], unique=False)
    op.create_unique_constraint(op.f('competitor_listings_tracked_product_id_url_key'), 'competitor_listings', ['tracked_product_id', 'url'], postgresql_nulls_not_distinct=False)
    op.drop_column('competitor_listings', 'render_type')
    op.drop_column('competitor_listings', 'discovered_api_endpoint')
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.create_foreign_key(op.f('alerts_price_snapshot_id_fkey'), 'alerts', 'price_snapshots', ['price_snapshot_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('alerts_user_id_fkey'), 'alerts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_competitor_listing_id'), table_name='alerts')
    op.create_index(op.f('idx_alerts_user'), 'alerts', ['user_id', 'is_read', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_alerts_listing'), 'alerts', ['competitor_listing_id'], unique=False)
    # ### end Alembic commands ###
