"""remove circular foreign key from scrape_jobs

Revision ID: ba53bd9e328c
Revises: b7596b093241
Create Date: 2026-05-17 14:12:09.817467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba53bd9e328c'
down_revision: Union[str, Sequence[str], None] = 'b7596b093241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('scrape_jobs_result_snapshot_id_fkey'), 'scrape_jobs', type_='foreignkey')
    op.drop_column('scrape_jobs', 'result_snapshot_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scrape_jobs', sa.Column('result_snapshot_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('scrape_jobs_result_snapshot_id_fkey'), 'scrape_jobs', 'price_snapshots', ['result_snapshot_id'], ['id'])
    # ### end Alembic commands ###
