"""Created a new search_columns

Revision ID: e40d05890b95
Revises: 5bad92d48d20
Create Date: 2026-07-25 14:18:40.365147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e40d05890b95'
down_revision: Union[str, Sequence[str], None] = '5bad92d48d20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracked_products', sa.Column('search_keyword', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracked_products', 'search_keyword')
    # ### end Alembic commands ###
