import uuid
from sqlalchemy import String, DateTime, ForeignKey, func, text, Integer, Text,SMALLINT,NUMERIC

from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship
from datetime import datetime
from app.database import Base
from typing import Optional,TYPE_CHECKING

if TYPE_CHECKING:
    from app.models.competitor_listing import CompetitorListing
    from app.models.price_snapshot import PriceSnapshot
    from app.models.scraper_profile import ScraperProfile


class ScrapeJob(Base):
    __tablename__ = "scrape_jobs"

    # Core IDs
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    competitor_listing_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("competitor_listings.id"), nullable=False, index=True
    )
    # Profile used for this specific job attempt
    profile_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("scraper_profiles.id"), nullable=True
    )

    # What was being scraped — a keyword ("iPhone 15 Pro") or a store URL.
    # Nullable because some job types (full crawl, health check) have no
    # specific target identifier.
    target_identifier: Mapped[str | None] = mapped_column(
        String(500),
        nullable=True
        # 500 chars covers any keyword or URL. Noon search URLs with
        # parameters are typically under 200 chars. 500 is safe.
    )

    # How many search result pages were scraped in this run.
    # Nullable because store scrapes don't have pages — they scrape all
    # products from a store in one pass.
    # SMALLINT: scrape runs are throttled. 50 pages per run is already
    # aggressive. Max 32,767 is more than enough.
    pages_scraped: Mapped[int | None] = mapped_column(
        SMALLINT,
        nullable=True
    )

    # Total products discovered during this scrape run.
    # INTEGER: a full category scrape could find tens of thousands of products.
    # SMALLINT (max 32,767) could theoretically be too small for large categories.
    items_found: Mapped[int | None] = mapped_column(
        nullable=True
    )


    # Products whose price or status actually changed in this run.
    # Always <= items_found. INTEGER for same reason.
    items_updated: Mapped[int | None] = mapped_column(
        nullable=True
    )

    # How many alerts were generated by this scrape run.
    # INTEGER: one run could theoretically generate alerts for every product.
    alerts_triggered: Mapped[int | None] = mapped_column(
        nullable=True
    )

    
    # How long the scrape run took in seconds.
    # NUMERIC(8,3): up to 99,999.999 seconds. Supports millisecond precision.
    # "This run took 142.847 seconds" is useful for performance monitoring.
    # Float would lose the millisecond precision due to floating point rounding.
    duration_secs: Mapped[float | None] = mapped_column(
        NUMERIC(8, 3),
        nullable=True
    )

    # The full error message if the run failed or partially failed.
    # Text (no length limit) because stack traces and error chains can be long.
    # You never want to truncate an error message — it might cut off the
    # exact line that tells you what went wrong.
    error_detail: Mapped[str | None] = mapped_column(
        Text,
        nullable=True
    )

    # Queue Logic
    # composite score: user tier + volatility + staleness
    priority_score: Mapped[int] = mapped_column(Integer, server_default=text("0"), nullable=False)
    
    # Status tracking (pending, running, done, failed)
    status: Mapped[str] = mapped_column(String(50), server_default="pending", nullable=False)
    failure_reason: Mapped[Optional[str]] = mapped_column(Text)
    attempt_number: Mapped[int] = mapped_column(Integer, server_default=text("1"), nullable=False)

    # Execution Timestamps
    scheduled_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    started_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    completed_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )


    extraction_method_used: Mapped[Optional[str]] = mapped_column(String(60),nullable=True)

    extraction_step_reached: Mapped[Optional[int]] = mapped_column(Integer,nullable=True)



    # Relationships (The Bridges)
    competitor_listing: Mapped["CompetitorListing"] = relationship(
    "CompetitorListing", back_populates="scrape_jobs",
    foreign_keys=[competitor_listing_id]
)
  
    profile: Mapped[Optional["ScraperProfile"]] = relationship(
    "ScraperProfile", back_populates="scrape_jobs"
)